name: "JS-CSS-Minifier"
description: "Minifier your CSS and JS code files"

author: "Sinith Hansaja <sinithdj@gmail.com>"

inputs:
  directory:
    description: "Directory that contains the files you want to minify. Defaults to current directory (.)"
    required: false
    default: "."
  output:
    description: "Directory that contains the minified files. Defaults to same directory"
    required: false
    default: ""

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "archive"
  color: "purple"